<a href="https://colab.research.google.com/github/saurabh2836/tensorflow-deep-learning/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this notebook, we're going to cover some of the most fundamental concepts of tensors using TensorFlow

More specifically,we're goimg to cover:


*   Introduction to tensors
*   Getting informations from tensors
*   Manipulating tensors
*   Tensors & NUmPy
*   using @tf.function ( a way to speed up your regular Pyhton functions )
*   Using GPUs with TensorFlow(or TPUs)
*   Exercises to try for yourself !! 





#Introduction to tensors

In [3]:
# Import TensorFlow

import tensorflow as tf
print(tf.__version__)

2.6.0


In [4]:
# Create tensors with tf.constant()

scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [5]:
# Check the number of dimensions of a tensor (ndim stands for number of dimensions)

scalar.ndim

0

In [6]:
# Create a Vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [8]:
vector.ndim

1

In [9]:
# Create a matrix (has more than 1 dimension)


matrix = tf.constant(
                      [[10,7],
                      [7,10]]
                     )
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [10]:
# Create Another Matrix


another_matrix = tf.constant([
                              [10.,7.],
                              [3.,2.],
                              [8.,9.]
                              ],dtype = tf.float16) # specify the data type with dtype parameter

another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>